#!/usr/bin/env bash
# Exports categories + products from nook.db into js/data.js as plain JS
# arrays, using sqlite3's built-in JSON1 functions. No Python, no Node,
# no server — the site just <script>-includes the result.
#
# Run this from the database/ folder any time you change data in nook.db:
#   bash export.sh
#
# (First time only: build the DB with
#   sqlite3 nook.db < schema.sql
#   sqlite3 nook.db < seed.sql
# )

set -euo pipefail
cd "$(dirname "$0")"

DB="nook.db"
OUT="../js/data.js"

if [ ! -f "$DB" ]; then
  echo "nook.db not found here. Run:"
  echo "  sqlite3 nook.db < schema.sql"
  echo "  sqlite3 nook.db < seed.sql"
  exit 1
fi

PRODUCTS_JSON=$(sqlite3 "$DB" "
  SELECT json_group_array(json_object(
    'id', id,
    'name', name,
    'category', category_id,
    'price', price,
    'oldPrice', old_price,
    'rating', rating,
    'stock', stock,
    'img', image_url,
    'badge', badge,
    'description', description
  ))
  FROM products;
")

CATEGORIES_JSON=$(sqlite3 "$DB" "
  SELECT json_group_array(json_object(
    'key', id,
    'label', name,
    'icon', icon
  ))
  FROM categories
  ORDER BY name;
")

cat > "$OUT" <<EOF
/* AUTO-GENERATED by database/export.sh from nook.db — do not edit by hand.
   Re-run 'bash database/export.sh' after changing data with sqlite3. */

const DB_PRODUCTS = ${PRODUCTS_JSON};
const DB_CATEGORIES = ${CATEGORIES_JSON};
EOF

COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM products;")
CAT_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM categories;")
echo "Exported ${CAT_COUNT} categories and ${COUNT} products to ${OUT}"
